## ASF meta-population model   

Based on ASF simulation model from Pepin et al. 2022, Optimizing response to an introduction of African Swine Fever in wild pigs, converted from Matlab to R/C++.    

All scripts/objects to run model should be here, with exception of two datasets used to model direct/indirect contact.

Email kim.m.pepin@usda.gov to request these datasets to run model. Else, just comment out references to ModelStateData.R and input parameters separately.    

Readme/scripts updated periodically.    

## Scripts

### Scripts to run simulation
* InitializeASFModel.R- run this once to load libraries, set paths, etc. 
* SetParameters.R- sets input parameters for model run
* ASFFunctionSourcer.R- source all functions needed to run simulation
* ML_R_Compare.R- takes output from ML/R models, make figures and summarise
* RunASFSimReplicates.R- run ASF simulation in loops, with different parameter settings, saves different outputs at end of each loop
* RunSimulationModel.R- runs each replicate of the ASF simulation-- initializes population and runs the model

### Simulation functions

### Output generating functions