#setwd(paste(home,"/Scripts/", sep = '')) 
source(paste(getwd(), "/Scripts/areaOfinfection.R", sep = ''))
source(paste(getwd(), "/Scripts/CullingOneRun.R", sep = ''))
source(paste(getwd(), "/Scripts/GenerateFakeStateData.R", sep = ''))
source(paste(getwd(), "/Scripts/InitializeSounders.R", sep = ''))
source(paste(getwd(), "/Scripts/Movement.R", sep = ''))
source(paste(getwd(), "/Scripts/SimulateOneRun.R", sep = ''))
source(paste(getwd(), "/Scripts/FOI.R", sep = ''))

#setwd(home) 
